
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email":"maria@mail.com",
    "password":"maria123456"
}

###Registro de usuario
POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json

{
    "name":"Maria",
    "email":"maria@mail.com",
    "password":"maria123456",
    "cpassword":"maria123456"
}

###Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 3|fvzZO5JzcrCQdClzSbg1bzpsUQoJ15StLGASUOFN8b384d75

###logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 3|fvzZO5JzcrCQdClzSbg1bzpsUQoJ15StLGASUOFN8b384d75
